name: Validate Student PR

on:
  pull_request:
    branches:
      - complete

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Echo PR SHA
        run: echo "this is going to work"
